-- Paginas del Administrador
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Registrar nuevos Proveedores","registrar_nuevos_proveedores.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Registrar nueva Marca","registrar_nueva_marca.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Registrar nueva Categoría","registrar_nueva_categoria.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Registrar nuevos Productos","registrar_nuevos_productos.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Actualizar Stock","actualizar_stock.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Asignar Oferta","asignar_oferta.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Producto Compuesto","registrar_produtco_compuesto.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Ver Stock de Productos","listado_stock.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Asignar Rol","asignar_roles.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Generar reporte","detalle_reporte.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Pedidos","listado_pedidos.aspx");

-- INSERT INTO ADMINISTRADOR X PAGINA
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,1);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,2);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,3);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,4);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,5);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,6);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,7);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,8);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,9);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,10);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(2,11);

-- Paginas de vendedor
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Pedidos","listado_pedidos_vendedor.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Ver Stock de Productos","listado_stock.aspx");

-- Almacenero x paginas
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(3,12);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(3,13);

-- Paginas de almacenero
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Pedidos","listado_pedidos_almacen.aspx");
INSERT INTO PAGINA (NOMBRE,REFERENCIA) VALUES("Ver Stock de Productos","listado_stock.aspx");

-- vendedor x paginas
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(4,14);
INSERT INTO TIPO_PERSONA_X_PAGINA (ID_TIPO_PERSONA, ID_PAGINA)VALUES(4,15);
