

INSERT INTO TIPO_PERSONA(NOMBRE, ACTIVO) VALUES ("CLIENTE",1);
INSERT INTO TIPO_PERSONA(NOMBRE, ACTIVO) VALUES ("ADMINISTRADOR",1);
INSERT INTO TIPO_PERSONA(NOMBRE, ACTIVO) VALUES ("VENDEDOR",1);
INSERT INTO TIPO_PERSONA(NOMBRE, ACTIVO) VALUES ("TRABAJADOR",1);
