INSERT INTO PERMISO (NOMBRE, DESCRIPCION, ACTIVO)values ("PERMISO 01", "ESTE ES EL PERMISO 01", 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, ACTIVO)values ("PERMISO 02", "ESTE ES EL PERMISO 02", 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, ACTIVO)values ("PERMISO 03", "ESTE ES EL PERMISO 03", 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, ACTIVO)values ("PERMISO 04", "ESTE ES EL PERMISO 04", 1);
INSERT INTO PERMISO (NOMBRE, DESCRIPCION, ACTIVO)values ("PERMISO 05", "ESTE ES EL PERMISO 05", 1);

/*insertar roles*/
INSERT INTO ROL (NOMBRE) VALUES ("CLIENTE");
INSERT INTO ROL (NOMBRE) VALUES ("ADMINISTRADOR");
INSERT INTO ROL (NOMBRE) VALUES ("VENDEDOR");
INSERT INTO ROL (NOMBRE) VALUES ("ALMACENERO");
/*Insertar los permisos para cada rol*/
/* permisos del cliente*/
INSERT INTO PERMISO_X_ROL (ID_ROL, ID_PERMISO) VALUES (1,1);
INSERT INTO PERMISO_X_ROL (ID_ROL, ID_PERMISO) VALUES (1,2);
INSERT INTO PERMISO_X_ROL (ID_ROL, ID_PERMISO) VALUES (1,3);
/* permisos del administrador*/
INSERT INTO PERMISO_X_ROL (ID_ROL, ID_PERMISO) VALUES (2,1);
INSERT INTO PERMISO_X_ROL (ID_ROL, ID_PERMISO) VALUES (2,2);
INSERT INTO PERMISO_X_ROL (ID_ROL, ID_PERMISO) VALUES (2,3);
INSERT INTO PERMISO_X_ROL (ID_ROL, ID_PERMISO) VALUES (2,4);
INSERT INTO PERMISO_X_ROL (ID_ROL, ID_PERMISO) VALUES (2,5);
/* permisos del vendedor*/
INSERT INTO PERMISO_X_ROL (ID_ROL, ID_PERMISO) VALUES (3,3);
/* permisos del almacenero*/
INSERT INTO PERMISO_X_ROL (ID_ROL, ID_PERMISO) VALUES (4,5);
