INSERT INTO TIPO_PERSONA(NOMBRE) VALUES ("CLIENTE");
INSERT INTO TIPO_PERSONA(NOMBRE) VALUES ("ADMINISTRADOR");
INSERT INTO TIPO_PERSONA(NOMBRE) VALUES ("VENDEDOR");
INSERT INTO TIPO_PERSONA(NOMBRE) VALUES ("TRABAJADOR");