SELECT 
    CLI.ID_CLIENTE,
    US.ID_USUARIO,US.DOCUMENTO,US.TELEFONO,
    US.NOMBRE,US.APELLIDO_PATERNO,US.APELLIDO_MATERNO,
    US.FECHA_NACIMIENTO,US.CORREO,US.DIRECCION,
    US.NACIONALIDAD,US.TIPO_DOCUMENTO
FROM 
    CLIENTE CLI
JOIN USUARIO  US ON CLI.ID_USUARIO = US.ID_USUARIO
    where US.ACTIVO = 1
    AND CLI.VERIFICADO = 1;


SELECT 
    CLI.ID_CLIENTE,
    US.ID_USUARIO,US.DOCUMENTO,US.TELEFONO,
    US.NOMBRE,US.APELLIDO_PATERNO,US.APELLIDO_MATERNO,
    US.FECHA_NACIMIENTO,US.CORREO,US.DIRECCION,
    US.NACIONALIDAD,US.TIPO_DOCUMENTO
FROM 
    CLIENTE CLI
JOIN USUARIO  US ON CLI.ID_USUARIO = US.ID_USUARIO
    where US.ACTIVO = 1
    AND CLI.VERIFICADO = 1
    AND CLI.ID_CLIENTE = 1; /*este 1 se va a cambiar en el JAVA POR ?*/ 