CREATE DEFINER=`admin`@`%` TRIGGER `INI_PRODUCTO_SEDE` AFTER INSERT ON `PRODUCTO` FOR EACH ROW BEGIN
	INSERT INTO PRODUCTO_X_SEDE(ID_PRODUCTO,ID_SEDE,STOCK_SEDE) SELECT DISTINCT
    (SELECT NEW.ID_PRODUCTO),
    SEDE.ID_SEDE,
    0
    FROM SEDE;
END